"use client";
import Navbar from "./components/Navbar";
import { CartProvider } from "./context/CartContext";
import "./globals.css";

export const metadata = {
  title: "Supermecado Dias",
  description: "Generated by Next.js",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <CartProvider>
        <head>
          <title>Supermecado Dias</title>
        </head>
        <body>
          <Navbar />
          {children}
        </body>
      </CartProvider>
    </html>
  );
}
